$ANSIBLE_VAULT;1.1;AES256
66363434663161643766393032303561383331613161333335383563663534636137373734353764
3632313939623234356631336530343234623463363361370a383139316333343865353439626638
30363338393363366339633764653036653738303230363264646632303138616437356136373137
6164633934613134630a323466666631663535643232363862303235333737623134363939333934
32363561643264363539646530363061343836363936616666666232633063333931396538313530
62623662656364373336323565636630613434383433336233333366616335633462633638343730
64323532646462336136326466663732303039663032353237656531396233336261336561356161
32336530656564613462333065313638333266306631633534333264343631643333303235343838
38303166666139623334396332663130366165363439363634356162653335613265356636306231
63663130373730323666333466656638666161396331373962616630323165343438346265376166
33653432336633613132383133373538633063333738383966303832653634633365323061393262
63623763303436363961
